[project]
name = "telecomx2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "pyjanitor>=0.32.19",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
]
